workspace:
  base: /go
  path: src/github.com/uesyn/docker-machine-driver-kcps

pipeline:
  build:
    image: golang:1.9
    commands:
     - apt update
     - apt install make
     - make

  s3:
    image: plugins/s3
    bucket: artifacts
    secrets: [ aws_access_key_id, aws_secret_access_key ]
    source: docker-machine-driver-kcps
    path_style: true
    endpoint: http://droneci.caaspoc.aws.kddi.com:9001
